apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: stepzen-graph-operator
    app.kubernetes.io/instance: stepzen-graph-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: stepzen-graph-operator
  name: stepzen-graph-operator
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: stepzen-graph-operator
    app.kubernetes.io/instance: stepzen-graph-leader-election-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: role
    app.kubernetes.io/part-of: stepzen-graph-operator
  name: stepzen-graph-leader-election-role
  
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: stepzen-graph-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stepzen-graph.ibm.com
  resources:
  - stepzengraphservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stepzen-graph.ibm.com
  resources:
  - stepzengraphservers/finalizers
  verbs:
  - update
- apiGroups:
  - stepzen-graph.ibm.com
  resources:
  - stepzengraphservers/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: stepzen-graph-operator
    app.kubernetes.io/instance: stepzen-graph-metrics-reader
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: stepzen-graph-operator
  name: stepzen-graph-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: stepzen-graph-operator
    app.kubernetes.io/instance: stepzen-graph-proxy-role
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: stepzen-graph-operator
  name: stepzen-graph-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stepzen-graph-webhook-role
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: stepzen-graph-operator
    app.kubernetes.io/instance: stepzen-graph-leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: stepzen-graph-operator
  name: stepzen-graph-leader-election-rolebinding
  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: stepzen-graph-leader-election-role
subjects:
- kind: ServiceAccount
  name: stepzen-graph-operator
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: stepzen-graph-operator
    app.kubernetes.io/instance: stepzen-graph-manager-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: stepzen-graph-operator
  name: stepzen-graph-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stepzen-graph-manager-role
subjects:
- kind: ServiceAccount
  name: stepzen-graph-operator
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: stepzen-graph-operator
    app.kubernetes.io/instance: stepzen-graph-proxy-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: stepzen-graph-operator
  name: stepzen-graph-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stepzen-graph-proxy-role
subjects:
- kind: ServiceAccount
  name: stepzen-graph-operator
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stepzen-graph-webhook-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stepzen-graph-webhook-role
subjects:
- kind: ServiceAccount
  name: stepzen-graph-operator
  
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: stepzen-graph-operator
    app.kubernetes.io/instance: stepzen-graph-metrics-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: stepzen-graph-operator
    control-plane: stepzen-graph-operator
  name: stepzen-graph-metrics-service
  
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: stepzen-graph-operator
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: stepzen-graph-operator
    app.kubernetes.io/instance: webhook-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: stepzen-graph-operator
  name: stepzen-graph-webhook-service
  
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: stepzen-graph-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    productID: 6ba6beb1cd3e49549b780f845293d546
    productMetric: FREE
    productName: IBM API Connect Essentials
  labels:
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: stepzen-graph-operator
    app.kubernetes.io/instance: stepzen-graph-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: deployment
    app.kubernetes.io/part-of: stepzen-graph-operator
    control-plane: stepzen-graph-operator
  name: stepzen-graph-operator
  
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: stepzen-graph-operator
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        productID: 6ba6beb1cd3e49549b780f845293d546
        productMetric: FREE
        productName: IBM API Connect Essentials
      labels:
        control-plane: stepzen-graph-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        env:
        - name: STEPZENGRAPHSERVER_IMAGE
          value: cp.icr.io/cp/stepzen/zenserv2@sha256:c77a1084d5782db320bb6e480c0189f0ce6a53683309afd44a9e164e0af6b078
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MUTATING_WEBHOOK
          value: stepzen-graph-mutating-webhook-configuration
        - name: VALIDATING_WEBHOOK
          value: stepzen-graph-validating-webhook-configuration
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ENABLE_WEBHOOKS
          value: "true"
        image: icr.io/cpopen/ibm-stepzen-graph-operator@sha256:136dde5ec6dffed676d6ac4109f3b6854f8460c1e3a16c5f0150d52e73127051
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: false
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=0
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 5m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      imagePullSecrets:
      - name: ibm-entitlement-key
      securityContext:
        runAsNonRoot: true
      serviceAccountName: stepzen-graph-operator
      terminationGracePeriodSeconds: 10
      volumes:
      - emptyDir: {}
        name: cert
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: stepzen-graph-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: stepzen-graph-webhook-service
      
      path: /mutate-stepzen-graph-ibm-com-v1beta1-stepzengraphserver
  failurePolicy: Fail
  name: mstepzengraphserver.kb.io
  rules:
  - apiGroups:
    - stepzen-graph.ibm.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - stepzengraphservers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: stepzen-graph-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: stepzen-graph-webhook-service
      
      path: /validate-stepzen-graph-ibm-com-v1beta1-stepzengraphserver
  failurePolicy: Fail
  name: vstepzengraphserver.kb.io
  rules:
  - apiGroups:
    - stepzen-graph.ibm.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - stepzengraphservers
  sideEffects: None
